before_script:
  - psql -c 'create database "kollektiv-leben_test";' -U postgres
language: ruby
rvm:
  - 2.3.0
test:
  adapter: postgresql
  database: kollektiv-leben_test
notifications:
  email: false
addons:
  code_climate:
    repo_token: ENV['CODECLIMATE_REPO_TOKEN']
after_success:
  - codeclimate-test-reporter
